"""补充的年龄分级规则。

本模块只包含「客观表意」规则：
- 二次元图片语境下常见、正常的内容尽量保持 general；
- 仅当 tag 客观上描述暴露服装、性暗示姿势/表情、真实武器、血腥或极端内容时才上调。
- 不考虑引申意、隐喻或梗文化含义。

用法：
    from .tag_classification_rules import EXTRA_EXACT_OVERRIDES, EXTRA_RATING_KEYWORDS
    EXACT_RATING_OVERRIDES.update(EXTRA_EXACT_OVERRIDES)
    for rating, kws in EXTRA_RATING_KEYWORDS.items():
        RATING_KEYWORDS.setdefault(rating, []).extend(kws)
"""

from __future__ import annotations

EXTRA_EXACT_OVERRIDES: dict[str, str] = {
    # ---------- 身体特征（general 居多，避免过严） ----------
    "breasts": "general",
    "huge breasts": "general",
    "large breasts": "general",
    "medium breasts": "general",
    "small breasts": "general",
    "flat chest": "general",
    "breast press": "r15",
    "breast squeeze": "r15",
    "breast lift": "r15",
    "breast smother": "r18",
    "breast expansion": "r15",
    "butt": "general",
    "ass": "general",
    "buttocks": "general",
    "ass grab": "r15",
    "butt grab": "r15",
    "grabbing own ass": "r15",
    "bare butt": "r18",
    "bare ass": "r18",
    "butt crack": "r18",
    "ass crack": "r18",
    "cameltoe": "r18",
    "crotch": "r15",
    "groin": "r15",
    "crotch seam": "r15",
    "ass visible through thighs": "r15",
    "armpit": "general",
    "armpits": "general",
    "armpit peek": "r15",
    "navel piercing": "pg12",
    "belly": "general",
    "stomach": "general",
    "abs": "general",
    "thighs": "general",
    "thick thighs": "general",
    "thigh gap": "general",
    "thigh grab": "r15",
    "hips": "general",
    "wide hips": "general",
    "hip vent": "pg12",
    "nipples": "r18",
    "nipple": "r18",
    "areola": "r18",

    # ---------- 服装 / 穿着状态 ----------
    "competition swimsuit": "pg12",
    "racing swimsuit": "pg12",
    "sukumizu": "pg12",
    "mizugi": "pg12",
    "bloomers": "pg12",
    "gym shorts": "pg12",
    "bike shorts": "pg12",
    "spats": "pg12",
    "sports bra": "pg12",
    "sports bikini": "pg12",
    "hot pants": "pg12",
    "short shorts": "pg12",
    "cutoff jeans": "pg12",
    "daisy dukes": "pg12",
    "halter top": "pg12",
    "tube top": "pg12",
    "sarashi": "pg12",
    "loincloth": "pg12",
    "speedo": "pg12",
    "swim trunks": "pg12",
    "zettai ryouiki": "pg12",
    "absolute territory": "pg12",
    "fundoshi": "r15",
    "male underwear": "r15",
    "men's underwear": "r15",
    "briefs": "r15",
    "boxer briefs": "r15",
    "g-string": "r15",
    "teddy": "r15",
    "bodystocking": "r15",
    "fishnets": "r15",
    "fishnet pantyhose": "r15",
    "latex": "r15",
    "rubber suit": "r15",
    "leather suit": "r15",
    "bondage outfit": "r15",
    "bdsm outfit": "r15",
    "harness": "r15",
    "naked apron": "r18",
    "apron only": "r15",
    "towel only": "r15",
    "open-crotch": "r18",
    "crotchless panties": "r18",
    "crotchless bikini": "r18",
    "open swimsuit": "r18",
    "nipple slip": "r18",
    "areola slip": "r18",
    "breast slip": "r18",
    "nipple peek": "r18",
    "areola peek": "r18",
    "pussy peek": "r18",
    "butt peek": "r15",
    "wardrobe malfunction": "r15",
    "clothing slip": "r15",
    "strap slip": "r15",
    "underwear down": "r15",
    "clothing aside": "r15",
    "clothes pull": "r15",
    "clothing pull": "r15",
    "panties around one leg": "r15",

    # ---------- 姿势 / 动作 ----------
    "lying down": "general",
    "on back": "general",
    "on stomach": "general",
    "reclining": "general",
    "kneeling": "general",
    "squatting": "general",
    "crouching": "general",
    "crawling": "general",
    "stretching": "general",
    "yoga": "general",
    "exercise": "general",
    "straddling": "r15",
    "straddle": "r15",
    "sitting on person": "r15",
    "sitting on lap": "pg12",
    "lap pillow": "general",
    "piggyback": "general",
    "kabedon": "pg12",
    "wall slam": "pg12",
    "bridal carry": "pg12",
    "hug from behind": "general",
    "french kiss": "r15",
    "spanking": "r18",
    "whipping": "r18",
    "caning": "r18",
    "flogging": "r18",
    "pole dancing": "r18",
    "lap dance": "r18",
    "twerking": "r18",
    "belly dancing": "pg12",
    "changing clothes": "pg12",
    "stripping": "r18",
    "undressing": "r18",
    "hand between legs": "r15",
    "holding both legs": "r15",
    "grabbing own legs": "r15",
    "grabbing both legs": "r15",
    "leg lock": "r15",
    "thigh lock": "r15",
    "scissor hold": "r15",
    "grappling": "r15",
    "wrestling": "r15",
    "pin": "r15",
    "mount": "r15",
    "spread legs": "r15",
    "legs apart": "r15",
    "leg up": "r15",
    "legs up": "r15",
    "bent over": "r15",
    "all fours": "r15",
    "arched back": "r15",
    "touching own thigh": "r15",
    "touching own breast": "r15",
    "touching own breasts": "r15",
    "touching own butt": "r15",
    "touching own crotch": "r18",
    "thigh grab": "r15",
    "breast grab": "r15",
    "grabbing own breast": "r15",
    "grabbing own breasts": "r15",
    "grabbing breasts": "r15",
    "butt grab": "r15",
    "ass grab": "r15",
    "hand on breast": "r15",
    "hand on butt": "r15",
    "hand on own chest": "general",
    "hand on own hip": "general",
    "hand on own face": "general",
    "covering privates": "r15",

    # ---------- 洗浴 / 场景 ----------
    "bathing": "pg12",
    "showering": "pg12",
    "onsen": "pg12",
    "hot spring": "pg12",
    "bathtub": "pg12",
    "shower room": "pg12",
    "sauna": "pg12",
    "bathhouse": "pg12",
    "locker room": "pg12",
    "changing room": "pg12",

    # ---------- 表情 / 反应 ----------
    "horny": "r18",
    "lustful": "r15",
    "lewd": "r18",
    "erotic": "r15",
    "sensual": "r15",
    "moaning": "r18",
    "heavy breathing": "r15",
    "panting": "r15",
    "drooling": "r15",
    "ahegao": "r18",
    "torogao": "r18",
    "doyagao": "general",
    "rolling eyes": "r15",
    "eyes rolling back": "r15",
    "heart-shaped pupils": "r15",
    "mind break": "r18",
    "disheveled": "pg12",
    "lovestruck": "general",
    "heart eyes": "general",
    "seductive": "r15",
    "bedroom eyes": "r15",
    "naughty face": "r15",
    "slutty face": "r15",
    "aroused": "r15",
    "aroused face": "r15",
    "arousal": "r15",
    "bimbo": "r15",
    "bimbo lip": "r15",
    "licking lips": "r15",
    "licking own lips": "r15",
    "biting lip": "r15",
    "hickey": "r15",
    "drunk": "r15",
    "intoxicated": "r15",
    "humiliation": "r15",
    "embarrassed": "general",
    "shy": "general",
    "blush": "general",
    "blush lines": "general",
    "tears": "general",
    "crying": "general",
    "sweat": "general",
    "sweatdrop": "general",
    "steaming body": "r15",
    "glistening body": "r15",
    "shiny skin": "general",
    "oiled": "r15",

    # ---------- 镜头 / 构图 ----------
    "close-up": "general",
    "between legs": "r15",
    "crotch focus": "r15",
    "breast focus": "r15",
    "butt focus": "r15",
    "ass focus": "r15",
    "lower body": "general",
    "upper body": "general",
    "full body": "general",
    "feet out of frame": "general",
    "head out of frame": "general",
    "pov": "general",
    "first person view": "general",
    "dutch angle": "general",
    "panty shot": "r15",
    "upskirt": "r15",
    "downblouse": "r15",
    "crotch shot": "r15",

    # ---------- 武器 / 暴力 ----------
    "water gun": "general",
    "toy gun": "general",
    "golf club": "general",
    "axe": "pg12",
    "scythe": "pg12",
    "halberd": "pg12",
    "lance": "pg12",
    "mace": "pg12",
    "flail": "pg12",
    "crossbow": "pg12",
    "katana": "pg12",
    "nunchaku": "pg12",
    "bo staff": "pg12",
    "dagger": "r15",
    "whip": "r15",
    "chainsaw": "r15",
    "machete": "r15",
    "club": "r15",
    "baseball bat": "r15",
    "brass knuckles": "r15",
    "rocket launcher": "r15",
    "grenade": "r15",
    "missile": "r15",
    "bomb": "r15",
    "landmine": "r15",
    "turret": "r15",
    "knife": "r15",
    "gun": "r15",
    "rifle": "r15",
    "pistol": "r15",
    "blade": "r15",
    "holding knife": "r15",
    "holding gun": "r15",
    "desert eagle": "r15",
    "slap": "r15",
    "stab": "r15",
    "stabbing": "r15",
    "choking": "r15",
    "strangling": "r15",
    "beating": "r15",
    "smother": "r15",
    "blood": "pg12",
    "blood on face": "pg12",
    "blood stain": "pg12",
    "blood from mouth": "r15",
    "bleeding": "r15",

    # ---------- 身体类型 / 性取向标签 ----------
    "futanari": "r15",
    "newhalf": "r15",
    "cuntboy": "r18",
    "dickgirl": "r18",
    "yaoi": "pg12",
    "yuri": "pg12",

    # ---------- 极端 / r18g ----------
    "vore": "r18g",
    "hard vore": "r18g",
    "soft vore": "r18g",
    "eye injury": "r18g",
    "missing eye": "r18g",
    "gouged eye": "r18g",
    "impaled": "r18g",
    "impalement": "r18g",
    "hanging": "r18g",
    "suicide": "r18g",
    "self harm": "r18g",
    "self-harm": "r18g",
    "cutting": "r18g",
    "broken bone": "r18g",
    "exposed bone": "r18g",
    "exposed muscle": "r18g",
    "exposed rib": "r18g",
    "exposed brain": "r18g",
    "exposed organ": "r18g",
    "rotting": "r18g",
    "cadaver": "r18g",
    "maimed": "r18g",
    "headless": "r18g",
    "severed head": "r18g",
    "detached head": "r18g",
    "holding detached head": "r18g",
    "amputee": "r18g",
    "amputated": "r18g",
    "amputation": "r18g",
    "dismembered": "r18g",
    "beheaded": "r18g", 
    "decapitated": "r18g", 
    "decapitation": "r18g",
    "disembowel": "r18g",
    "disembowelment": "r18g",
    "internal organs": "r18g",
    "intestine": "r18g",
    "intestines": "r18g",
    "viscera": "r18g",
    "prolapse": "r18g",
    "rectal prolapse": "r18g",
    "mutilated": "r18g",
    "mutilation": "r18g",
    "flayed": "r18g",
    "skinned alive": "r18g",
    "corpse": "r18g",
    "dead body": "r18g",
    "death": "r18g",
    "dying": "r18g",
    "murder": "r18g",
    "snuff": "r18g",
    "necrophilia": "r18g",
    "ryona": "r18g",
    "torture": "r18g",
    "asphyxia": "r18g",
    "asphyxiation": "r18g",
    "strangled": "r18g",
    "garrote": "r18g",
    "lynching": "r18g",
    "crucifixion": "r18g",
    "gore": "r18g",
    "blood splatter": "r18g",
    "cannibalism": "r18g",
    "feces": "r18g",
    "scat": "r18g",
    "poop": "r18g",
    "shit": "r18g",
    "urine": "r18g",
    "pee": "r18g",
    "piss": "r18g",
    "vomit": "r18g",
    "snot": "r18g",
    "menstruation": "r18g",
    "period blood": "r18g",
    "enema": "r18g",
    "diarrhea": "r18g",
    "fart": "r18g",
    "flatulence": "r18g",
    "bestiality": "r18g",
    "zoophilia": "r18g",
    "incest": "r18g",
    "rape": "r18g",
    "pedophile": "r18g",

    # ---------- 二次元常见误伤标签修正 ----------
    # 装饰/蝴蝶结（与比基尼系带无关）
    "bow": "general",
    "hair bow": "general",
    "hat bow": "general",
    "ear bow": "general",
    "tail bow": "general",
    "dress bow": "general",
    "waist bow": "general",
    "footwear bow": "general",
    "sleeve bow": "general",
    "back bow": "general",
    "centered hair bow": "general",
    "large bow": "general",
    "print bow": "general",
    "two-tone bow": "general",
    "polka dot bow": "general",
    "diagonal-striped bow": "general",
    "striped bow": "general",
    "plaid bow": "general",
    "red bow": "general",
    "black bow": "general",
    "blue bow": "general",
    "white bow": "general",
    "pink bow": "general",
    "yellow bow": "general",
    "green bow": "general",
    "purple bow": "general",
    "orange bow": "general",
    "frilled bow": "general",
    "aqua bow": "general",
    "grey bow": "general",
    "brown bow": "general",
    "bow (feature)": "general",
    "bow tie": "general",
    "gift bow": "general",

    # 常见发型 / 绑发（与捆绑无关）
    "tied hair": "general",
    "multi-tied hair": "general",
    "low-tied long hair": "general",
    "short hair with long locks": "general",
    "bow-shaped hair": "general",

    # 身体特征（客观非性意味）
    "navel hair": "general",
    "deep navel": "general",
    "non-mammal navel": "general",
    "outie navel": "general",
    "belly": "general",
    "butt hair": "general",
    "freckled butt": "general",
    "abs": "general",
    "midriff peek": "pg12",
    "navel peek": "pg12",
    "collarbone": "general",
    "shoulders": "general",

    # 绷带 / 包扎（医疗/装饰）
    "bandaged hand": "pg12",
    "bandaged neck": "pg12",
    "bandaged arm": "pg12",
    "bandaged leg": "pg12",
    "bandaged face": "pg12",
    "bandages": "pg12",
    "bandage": "pg12",
    "bandaged": "pg12",
    "bandaged head": "pg12",

    # 血迹 / 轻伤
    "blood on arm": "pg12",
    "blood on leg": "pg12",
    "blood from eyes": "pg12",
    "blood in hair": "pg12",
    "blood tears": "pg12",
    "blood on mouth": "pg12",
    "blood on cheek": "pg12",
    "blood in mouth": "pg12",
    "bruise on face": "pg12",
    "bruised face": "pg12",
    "slap mark on face": "pg12",
    "bite mark on face": "pg12",
    "scar across eyes": "general",
    "scar on face": "pg12",
    "scar on cheek": "pg12",
    "scar across eye": "pg12",

    # 服装状态（无必然性暗示）
    "off-shoulder dress": "pg12",
    "off-shoulder shirt": "pg12",
    "off shoulder": "pg12",
    "strapless dress": "pg12",
    "strapless shirt": "pg12",
    "strapless": "pg12",
    "unzipped": "pg12",
    "backless dress": "pg12",
    "backless": "pg12",
    "side slit": "pg12",
    "shorts under skirt": "general",
    "bike shorts under skirt": "general",
    "bikini skirt": "pg12",
    "bikini armor": "pg12",
    "bikini top only": "pg12",
    "bikini bottom only": "pg12",
    "bikini bottom aside": "pg12",
    "swimsuit aside": "pg12",
    "front-tie bikini top": "pg12",

    # "only" 类仅表示穿戴单一物品，无裸露含义
    "hat only": "general",
    "gloves only": "general",
    "socks only": "general",
    "shirt only": "general",
    "jacket only": "general",
    "boots only": "general",
    "jewelry only": "general",

    # 手持物品（水枪、高尔夫球杆等玩具/运动器材）
    "holding water gun": "general",
    "water gun": "general",
    "holding golf club": "general",
    "golf club": "general",
    "toy gun": "general",
    "holding toy gun": "general",
    "fighting pose": "general",
    "bent over table": "pg12",
    "bent over desk": "pg12",

    # 表情 / 嘴部异常（身体恐怖）
    "stitched mouth": "r18g",
    "sewn mouth": "r18g",
    "rape face": "r18",
    "shit eating grin": "general",
    "tired of this shit": "general",
    "butt mouth": "r15",

    # 场景物品（悬挂是物理状态，非自杀）
    "hanging plant": "general",
    "hanging light": "general",
    "hanging": "r18g",
    "lynching": "r18g",

    # 动物 / 角色类型（ furry 等）
    "anthro": "general",
    "furry": "general",
    "kemono": "general",
    "kemonomimi mode": "general",
    "taur": "general",

    # 其他边界修正
    "pregnant male": "general",
    "futa with male": "general",
    "clothed male nude male": "r18",
    "cuntboy with male": "r18",
    "clothed ambiguous nude male": "r18",
    "partially clothed female nude male": "r18",
    "partially clothed anthro nude male": "r18",
    "mostly nude human": "r18",
    "mostly nude male": "r18",
    "topless human": "r18",
    "nude male": "r18",
    "nude human": "r18",
    "suicide boy": "r18g",
    "bawdy art": "r15",
    "soft gore": "r18g",

    # 泳装 / 内衣细分
    "black tank top": "general",
    "white tank top": "general",
    "camisole": "pg12",
    "nightgown": "pg12",
    "polka dot panties": "r15",
    "striped panties": "r15",
    "frilled panties": "r15",
    "lace-trimmed panties": "r15",
    "print panties": "r15",
    "white panties": "r15",
    "black panties": "r15",
    "blue panties": "r15",
    "pink panties": "r15",
    "red panties": "r15",
    "green panties": "r15",
    "purple panties": "r15",
    "yellow panties": "r15",

    # 丝袜 / 裤袜（二次元常见穿搭）
    "pantyhose": "pg12",
    "stockings": "pg12",
    "tights": "pg12",
    "fishnet pantyhose": "r15",
    "fishnets": "r15",
    "fishnet": "r15",
    "thighhighs": "pg12",
    "over-kneehighs": "pg12",
    "kneehighs": "general",
}

EXTRA_RATING_KEYWORDS: dict[str, list[str]] = {
    "r18g": [
        # 极端暴力 / 血腥
        "vore",
        "hard vore",
        "soft vore",
        "impaled",
        "impalement",
        "eye injury",
        "missing eye",
        "gouged eye",
        "eyeball",
        "suicide",
        "self harm",
        "self-harm",
        "cutting",
        "broken bone",
        "exposed bone",
        "exposed muscle",
        "exposed rib",
        "exposed brain",
        "exposed organ",
        "rotting",
        "cadaver",
        "maimed",
        "guro",
    ],
    "r18": [
        # 暴露服装 / 动作
        "naked apron",
        "apron only",
        "stripping",
        "strip",
        "pole dancing",
        "lap dance",
        "twerking",
        "spanking",
        "whipping",
        "caning",
        "flogging",
        # 性行为 / 反应
        "moaning",
        "ahegao",
        "torogao",
        "mind break",
        "orgasmic",
        # 性器官 / 暴露
        "cameltoe",
        "butt crack",
        "ass crack",
        "crotchless",
        "breast smother",
        "facesitting",
        "face sitting",
        "open-crotch",
        # 身体类型俚语
        "cuntboy",
        "dickgirl",
        # 强烈性暗示
        "horny",
        "lewd",
        "nipple slip",
        "areola slip",
        "breast slip",
        "nipple peek",
        "areola peek",
        "pussy peek",
        "undressing",
        "touching own crotch",
    ],
    "r15": [
        # 内衣 / fetish 服装
        "teddy",
        "bodystocking",
        "fishnets",
        "fishnet",
        "latex",
        "rubber suit",
        "leather suit",
        "bondage outfit",
        "bdsm outfit",
        "harness",
        "fundoshi",
        "male underwear",
        "men's underwear",
        "briefs",
        "boxer briefs",
        "g-string",
        # 走光 / 暴露状态
        "wardrobe malfunction",
        "clothing slip",
        "strap slip",
        "butt peek",
        "underwear down",
        "clothing aside",
        "clothes pull",
        "clothing pull",
        "panties around one leg",
        # 姿势 / 动作
        "straddling",
        "straddle",
        "sitting on person",
        "leg lock",
        "thigh lock",
        "scissor hold",
        "grappling",
        "wrestling",
        "pin",
        "mount",
        "wall slam",
        "kabedon",
        "spread legs",
        "legs apart",
        "leg up",
        "legs up",
        "bent over",
        "all fours",
        "arched back",
        "hand between legs",
        "holding both legs",
        "grabbing own legs",
        "grabbing both legs",
        "touching own thigh",
        "touching own breast",
        "touching own breasts",
        "touching own butt",
        "thigh grab",
        "breast grab",
        "grabbing own breast",
        "grabbing own breasts",
        "grabbing breasts",
        "butt grab",
        "ass grab",
        "hand on breast",
        "hand on butt",
        "covering privates",
        # 表情
        "lustful",
        "erotic",
        "sensual",
        "heavy breathing",
        "panting",
        "drooling",
        "rolling eyes",
        "eyes rolling back",
        "heart-shaped pupils",
        "seductive",
        "bedroom eyes",
        "naughty face",
        "slutty face",
        "aroused",
        "arousal",
        "bimbo",
        "licking lips",
        "licking own lips",
        "biting lip",
        "hickey",
        "drunk",
        "intoxicated",
        "humiliation",
        "steaming body",
        "glistening body",
        "oiled",
        # 身体部位 / 触摸
        "butt",
        "ass",
        "buttocks",
        "ass grab",
        "butt grab",
        "grabbing own ass",
        "grabbing own butt",
        "bare butt",
        "bare ass",
        "crotch",
        "groin",
        "crotch seam",
        "ass visible through thighs",
        "armpit peek",
        "thigh grab",
        "hip vent",
        # 镜头
        "between legs",
        "crotch focus",
        "breast focus",
        "butt focus",
        "ass focus",
        "panty shot",
        "upskirt",
        "downblouse",
        "crotch shot",
        # 场景
        "onsen",
        "hot spring",
        "locker room",
        "changing room",
        "shower room",
        "sauna",
        "bathhouse",
        # 武器 / 暴力
        "whip",
        "chainsaw",
        "machete",
        "dagger",
        "club",
        "brass knuckles",
        "rocket launcher",
        "grenade",
        "missile",
        "bomb",
        "landmine",
        "turret",
        "knife",
        "gun",
        "rifle",
        "pistol",
        "blade",
        "holding knife",
        "holding gun",
        "slap",
        "stab",
        "stabbing",
        "choking",
        "strangling",
        "beating",
        "smother",
        "blood from mouth",
        "bleeding",
        # 身体类型
        "futanari",
        "newhalf",
    ],
    "pg12": [
        # 泳装 / 运动服变体
        "competition swimsuit",
        "racing swimsuit",
        "sukumizu",
        "mizugi",
        "bloomers",
        "gym shorts",
        "bike shorts",
        "spats",
        "sports bra",
        "sports bikini",
        "hot pants",
        "short shorts",
        "cutoff jeans",
        "daisy dukes",
        "halter top",
        "tube top",
        "sarashi",
        "loincloth",
        "speedo",
        "swim trunks",
        "zettai ryouiki",
        "absolute territory",
        "swimsuit",
        "bikini",
        "one-piece swimsuit",
        "school swimsuit",
        "gym uniform",
        "buruma",
        "sportswear",
        "miniskirt",
        "crop top",
        "tank top",
        "shorts",
        "skirt lift",
        "torn clothes",
        "cleavage",
        "off shoulder",
        "backless",
        "strapless",
        "side slit",
        "midriff",
        "navel",
        "bare shoulders",
        "bare back",
        "zettai ryouiki",
        # 舞蹈 / 亲密姿势
        "belly dancing",
        "sitting on lap",
        "lap pillow",
        "bridal carry",
        "changing clothes",
        "kabedon",
        "wall slam",
        # 洗浴场景
        "bathing",
        "showering",
        "bathtub",
        "shower room",
        "sauna",
        "bathhouse",
        "onsen",
        "hot spring",
        "locker room",
        "changing room",
        # 身体 / 状态
        "navel piercing",
        "disheveled",
        "blood",
        "blood on face",
        "blood stain",
        "scar on face",
        "scar on cheek",
        "scar across eye",
        "bandaged head",
        "bandaged arm",
        "cracked skin",
        "missing leg",
        "missing arm",
        # 武器
        "axe",
        "scythe",
        "halberd",
        "lance",
        "mace",
        "flail",
        "crossbow",
        "katana",
        "nunchaku",
        "bo staff",
        "sword",
        "weapon",
        "holding sword",
        "holding weapon",
        "shield",
        "spear",
        "bow",
        "bow and arrow",
        "arrow",
        "staff",
        "wand",
        "fighting",
        "battle",
        "punching",
        "kicking",
        "bite",
        "fighting stance",
        "battle stance",
        "action pose",
        "dynamic pose",
        # 表情
        "angry",
        "serious",
        "determined",
        "annoyed",
        "cigarette",
        "smoking",
        "drunk",
    ],
}


#: 用户手工精选的 r18 白名单（类别 -> tag 列表）。
#: 构建 curated_tags.yaml 时，这些 tag 无条件保留并评 r18，不受 top_n 截断影响；
#: 运行期 r18 模式下也会被纳入可抽取池。
R18_MANUAL_WHITELIST: dict[str, list[str]] = {
    "appearance": [
        "armpit fetish",
        "exposed belly",
        "exposed breasts",
        "exposed chest",
        "exposed shoulder",
        "nipple outline",
        "nipple slip",
        "nipple tag",
        "nipple-to-nipple",
        "older penetrated",
        "topless female",
        "whip marks",
        "whipped",
        "younger penetrated",
    ],
    "clothing_state": [
        "bdsm outfit",
        "black blindfold",
        "blindfold",
        "blindfold lift",
        "blindfold slip",
        "bondage gear",
        "bondage harness",
        "bondage mittens",
        "bondage outfit",
        "crotch rope",
        "cummerbund",
        "exposed panties",
        "exposed pocket",
        "exposed underwear",
        "fetish wear",
        "gag around neck",
        "gag harness",
        "gag under mask",
        "harness gag",
        "leash between breasts",
        "naked apron",
        "naked armor",
        "naked bandage",
        "naked belt",
        "naked bowtie",
        "naked cape",
        "naked capelet",
        "naked cardigan",
        "naked cloak",
        "naked costume",
        "naked gloves",
        "naked hood",
        "naked hoodie",
        "naked jacket",
        "naked kimono",
        "naked necktie",
        "naked overalls",
        "naked poncho",
        "naked raincoat",
        "naked ribbon",
        "naked robe",
        "naked scarf",
        "naked sheet",
        "naked skirt",
        "naked suspenders",
        "naked sweater",
        "naked tabard",
        "naked towel",
        "naked vest",
        "nearly naked apron",
        "nipple bar",
        "nipple bells",
        "nipple chain",
        "nipple covers",
        "nipple cutout",
        "nipple jewelry",
        "nipple leash",
        "nipple piercing",
        "nipple ribbon",
        "nipple rings",
        "nipple tape",
        "nipple tassels",
        "nipple weights",
        "no blindfold",
        "no panties",
        "over the mouth gag",
        "panty gag",
        "partially undressed",
        "pussy piercing",
        "red blindfold",
        "red leash",
        "single nipple piercing",
        "spread cleavage",
        "torn blindfold",
        "unworn blindfold",
        "white blindfold",
    ],
    "pose_action_sex": [
        "after cunnilingus",
        "after ejaculation",
        "after fingering",
        "after masturbation",
        "after orgasm",
        "assisted masturbation",
        "biting nipple",
        "breast bondage",
        "clitoral stimulation",
        "clitoral stimulation through clothing",
        "clitoris pull",
        "clitoris torture",
        "clitoris tweak",
        "clothed female nude female",
        "clothed masturbation",
        "clothes gag",
        "covering anus",
        "covering one nipple",
        "cumdrip",
        "cumdrip onto panties",
        "cumdrip through clothes",
        "cumdrip through panties",
        "cumming while penetrating",
        "cumshot",
        "cumshot in mouth",
        "cumshot on face",
        "cunnilingus",
        "cunnilingus gesture",
        "cunnilingus through clothes",
        "dildo riding",
        "double masturbation",
        "ejaculation",
        "ejaculation under clothes",
        "female ejaculation",
        "female ejaculation through clothes",
        "female masturbation",
        "female orgasm",
        "female penetrated",
        "fingering",
        "fingering from behind",
        "fingering partner",
        "fingering through clothes",
        "fingering through panties",
        "fingers in pussy",
        "foot fetish",
        "forced masturbation",
        "forced orgasm",
        "hair bondage",
        "hand gag",
        "handsfree ejaculation",
        "holding blindfold",
        "holding gag",
        "holding handcuffs",
        "holding own leash",
        "human penetrating",
        "imminent fingering",
        "imminent masturbation",
        "imminent orgasm",
        "implied after masturbation",
        "implied cunnilingus",
        "implied ejaculation",
        "implied fingering",
        "implied masturbation",
        "intense orgasm",
        "internal cumshot",
        "kissing while penetrated",
        "larger penetrated",
        "leash in mouth",
        "leash pull",
        "licking dildo",
        "licking nipple",
        "licking own nipple",
        "lipstick mark on pussy",
        "masturbating while watching",
        "masturbation",
        "masturbation through clothes",
        "masturbation through clothing",
        "mutual fingering",
        "mutual masturbation",
        "mutual orgasm",
        "naked dogeza",
        "navel fingering",
        "nipple bondage",
        "nipple flick",
        "nipple injection",
        "nipple pinch",
        "nipple play",
        "nipple pull",
        "nipple rub",
        "nipple stimulation",
        "nipple suck",
        "nipple torture",
        "nipple tweak",
        "nipple tweak through clothes",
        "nude modeling",
        "nursing fingering",
        "object in pussy",
        "orgasm",
        "orgasm denial",
        "otm gag",
        "predicament bondage",
        "presenting pussy",
        "public bondage",
        "public masturbation",
        "pussy cutout",
        "pussy ejaculation",
        "pussy grip",
        "pussy juice drip through clothes",
        "pussy juice in mouth",
        "pussy juice on face",
        "pussy juice on fingers",
        "pussy juice on panties",
        "pussy juice stain",
        "pussy juice string",
        "pussy juice trail",
        "pussy peek",
        "pussy sandwich",
        "pussy torture",
        "rear naked choke",
        "ribbon bondage",
        "riding dildo",
        "ruined orgasm",
        "self bondage",
        "sex toy insertion",
        "smaller penetrated",
        "smelling anus",
        "snake bondage",
        "spread anus under clothes",
        "spread armpit",
        "spread ass",
        "spread butt",
        "spread legs",
        "spread pussy",
        "spread urethra",
        "spreading another's anus",
        "spreading another's pussy",
        "spreading own anus",
        "spreading own pussy",
        "standing cunnilingus",
        "stealth bondage",
        "stealth fingering",
        "stealth masturbation",
        "tail bondage",
        "tail masturbation",
        "tape bondage",
        "tentacle in pussy",
        "tongue in pussy",
        "tweaking own nipple",
        "two-handed masturbation",
        "undressing",
        "undressing another",
        "undressing partner",
        "undressing self",
        "urethral fingering",
        "vaginal fingering",
        "vaginal masturbation",
        "water masturbation",
        "whipping",
    ],
    "expression_reaction": [
        "cleave gag",
        "looking at pussy",
    ],
    "camera_shot": [
        "penetrating pov",
        "pussy focus",
        "viewer holding leash",
        "viewer on leash",
    ],
    "scene_environment": [
        "ball and chain restraint",
        "bondage",
        "broken handcuffs",
        "chain leash",
        "chain whip",
        "chocolate on pussy",
        "cloth gag",
        "energy whip",
        "fuzzy handcuffs",
        "gag",
        "handcuff dangle",
        "handcuffed",
        "handcuffs",
        "improvised gag",
        "leash",
        "naked chocolate",
        "nude beach",
        "open mouth gag",
        "pussy juice puddle",
        "restraints",
        "shared handcuffs",
        "single handcuff",
        "stationary restraints",
        "stripper pole",
        "tape gag",
        "upright restraints",
        "vine whip",
        "whip",
        "whipped cream",
    ],
    "detail_mood": [
        "gag manga biyori",
        "nude cover",
        "nude filter",
        "panel gag",
    ],
}
